/**
 * @file types.ts
 * @description This file contains TypeScript interfaces for the core data models
 * used throughout the application, ensuring type safety and consistency.
 * This program was written by Stuart Mason October 2025.
 */

// Represents a tabletop gaming system, e.g., "Warhammer 40,000".
export interface GameSystem {
  id: string; // Unique identifier, typically generated by the database.
  name: string; // The display name of the game system.
  // Optional color scheme for dynamic theming of the UI.
  colorScheme?: {
    primary: string; // Main accent color for buttons, links, etc.
    secondary: string; // Secondary accent color.
    background: string; // A background color that fits the theme.
  };
}

// Represents an army or faction within a specific game system.
export interface Army {
  id:string; // Unique identifier.
  name:string; // The display name of the army, e.g., "Space Marines".
  gameSystemId: string; // A foreign key that links this army to a GameSystem.
}

// Represents a step in a model's painting recipe.
export interface PaintRecipeStep {
  paintId: string; // Foreign key linking to a Paint object.
  usage: string;   // Description of how the paint is used, e.g., "Armor Basecoat".
}

// Represents a single miniature model in the user's collection.
export interface Model {
  id: string; // Unique identifier for the model entry.
  name: string; // The name of the model, e.g., "Primaris Intercessor".
  armyIds: string[]; // An array of foreign keys, allowing a model to belong to multiple armies (e.g., a mercenary).
  gameSystemId: string; // A foreign key linking this model to a primary GameSystem.
  description: string; // A text description, which can include lore or gameplay notes.
  quantity: number; // How many of this specific model the user owns.
  status: 'Purchased' | 'Printed' | 'Assembled' | 'Primed' | 'Painted' | 'Based' | 'Ready to Game'; // The current stage in the painting/hobby process.
  imageUrl?: string; // Optional URL or base64 data string for an image of the model.
  paintingNotes?: string; // Optional field for storing paint recipes, colors used, or other hobby notes.
  paintRecipe?: PaintRecipeStep[]; // An array of steps defining the paint recipe.
  createdAt: string; // ISO 8601 date string of when the model was created.
  lastUpdated: string; // ISO 8601 date string of when the model was last updated.
}

// Represents a painting session event for the calendar.
export interface PaintingSession {
  id: string; // Unique identifier.
  title: string; // The title or goal of the session.
  start: string; // ISO 8601 date string for the start time.
  end: string;   // ISO 8601 date string for the end time.
  notes?: string; // Optional notes or details.
  modelIds: string[]; // An array of Model IDs linked to this session.
  gameSystemId?: string; // Optional foreign key linking to a GameSystem.
}

// Represents a single paint in the user's collection.
export interface Paint {
  id: string; // Unique identifier.
  name: string; // The name of the paint, e.g., "Macragge Blue".
  paintType: 'Base' | 'Layer' | 'Shade' | 'Contrast' | 'Technical' | 'Dry' | 'Air' | 'Metallic'; // The type of paint.
  manufacturer: string; // The company that produces the paint, e.g., "Citadel".
  colorScheme: string; // The general color family, e.g., "Blue", "Metallic".
  rgbCode?: string; // Optional hex or RGB code for the color, e.g., "#0d4e8a" or "rgb(13, 78, 138)".
  stock: number; // The quantity of this paint the user owns.
}

// Represents a temporary notification message (a "toast") shown to the user.
export type ToastMessage = {
  id: number; // A unique ID (often a timestamp) for managing the toast's lifecycle.
  message: string; // The text content of the notification.
  type: 'success' | 'error'; // The type of toast, used for styling (e.g., green for success, red for error).
};