/// <reference types="vite/client" />

/**
 * @file apiService.ts
 * @description This service provides functions for interacting with the backend API.
 * It encapsulates all HTTP requests (using `fetch`) for CRUD operations on game systems, armies, and models.
 * Centralizing API calls here makes the components cleaner and the codebase easier to maintain.
 * This program was written by Stuart Mason October 2025.
 */

import { GameSystem, Army, Model, PaintingSession, Paint } from '../types';

// The base URL for the backend API. It uses an environment variable for production/staging
// and falls back to the local server URL for development.
const API_BASE_URL = import.meta.env.VITE_API_BASE_URL || 'http://localhost:3001/api';

// A helper function to handle fetch responses consistently.
// It checks if the response was successful (status 200-299). If not, it throws an error.
// If successful, it parses the JSON body of the response.
const handleResponse = async <T>(response: Response): Promise<T> => {
  if (!response.ok) {
    // Try to parse error details from the response body, otherwise provide a generic message.
    const errorData = await response.json().catch(() => ({ message: 'An unknown error occurred' }));
    throw new Error(errorData.message || `HTTP error! status: ${response.status}`);
  }
  return response.json();
};

// --- Game System API calls ---

/** Fetches all game systems from the server. */
export const getGameSystems = async (): Promise<GameSystem[]> => {
  const response = await fetch(`${API_BASE_URL}/game-systems`);
  return handleResponse<GameSystem[]>(response);
};

/** Adds a new game system to the database. */
export const addGameSystem = async (system: Omit<GameSystem, 'id'>): Promise<GameSystem> => {
  const response = await fetch(`${API_BASE_URL}/game-systems`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(system),
  });
  return handleResponse<GameSystem>(response);
};

/** Updates an existing game system. */
export const updateGameSystem = async (id: string, system: Partial<Omit<GameSystem, 'id'>>): Promise<GameSystem> => {
    const response = await fetch(`${API_BASE_URL}/game-systems/${id}`, {
      method: 'PUT', // or 'PATCH' depending on the API design
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(system),
    });
    return handleResponse<GameSystem>(response);
  };
  
/** Deletes a game system by its ID. */
export const deleteGameSystem = async (id: string): Promise<void> => {
  const response = await fetch(`${API_BASE_URL}/game-systems/${id}`, {
    method: 'DELETE',
  });
  // DELETE requests often don't return a body, so we just check for success.
  if (!response.ok) {
    throw new Error('Failed to delete game system');
  }
};


// --- Army API calls ---

/** Fetches all armies. */
export const getArmies = async (): Promise<Army[]> => {
  const response = await fetch(`${API_BASE_URL}/armies`);
  return handleResponse<Army[]>(response);
};

/** Adds a new army. */
export const addArmy = async (army: Omit<Army, 'id'>): Promise<Army> => {
    const response = await fetch(`${API_BASE_URL}/armies`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(army),
    });
    return handleResponse<Army>(response);
};
  
/** Updates an existing army. */
export const updateArmy = async (id: string, army: Partial<Omit<Army, 'id'>>): Promise<Army> => {
    const response = await fetch(`${API_BASE_URL}/armies/${id}`, {
        method: 'PUT',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(army),
    });
    return handleResponse<Army>(response);
};

/** Deletes an army by its ID. */
export const deleteArmy = async (id: string): Promise<void> => {
  const response = await fetch(`${API_BASE_URL}/armies/${id}`, {
    method: 'DELETE',
  });
  if (!response.ok) {
    throw new Error('Failed to delete army');
  }
};


// --- Model API calls ---

/** Fetches all models. */
export const getModels = async (): Promise<Model[]> => {
  const response = await fetch(`${API_BASE_URL}/models`);
  return handleResponse<Model[]>(response);
};

/** Adds a new model. */
// FIX: The type for a new model should not include id, createdAt, or lastUpdated,
// as these are generated by the server. This resolves type errors in DataContext.
export const addModel = async (model: Omit<Model, 'id' | 'createdAt' | 'lastUpdated'>): Promise<Model> => {
    const response = await fetch(`${API_BASE_URL}/models`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(model),
    });
    return handleResponse<Model>(response);
};

/** Updates an existing model. */
export const updateModel = async (id: string, model: Partial<Omit<Model, 'id'>>): Promise<Model> => {
    const response = await fetch(`${API_BASE_URL}/models/${id}`, {
        method: 'PUT',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(model),
    });
    return handleResponse<Model>(response);
};

/** Deletes a model by its ID. */
export const deleteModel = async (id: string): Promise<void> => {
  const response = await fetch(`${API_BASE_URL}/models/${id}`, {
    method: 'DELETE',
  });
  if (!response.ok) {
    throw new Error('Failed to delete model');
  }
};

// --- Painting Session API calls ---

/** Fetches all painting sessions. */
export const getPaintingSessions = async (): Promise<PaintingSession[]> => {
  const response = await fetch(`${API_BASE_URL}/painting-sessions`);
  return handleResponse<PaintingSession[]>(response);
};

/** Adds a new painting session. */
export const addPaintingSession = async (session: Omit<PaintingSession, 'id'>): Promise<PaintingSession> => {
    const response = await fetch(`${API_BASE_URL}/painting-sessions`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(session),
    });
    return handleResponse<PaintingSession>(response);
};

/** Updates an existing painting session. */
export const updatePaintingSession = async (id: string, session: Partial<Omit<PaintingSession, 'id'>>): Promise<PaintingSession> => {
    const response = await fetch(`${API_BASE_URL}/painting-sessions/${id}`, {
        method: 'PUT',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(session),
    });
    return handleResponse<PaintingSession>(response);
};

/** Deletes a painting session by its ID. */
export const deletePaintingSession = async (id: string): Promise<void> => {
  const response = await fetch(`${API_BASE_URL}/painting-sessions/${id}`, {
    method: 'DELETE',
  });
  if (!response.ok) {
    throw new Error('Failed to delete painting session');
  }
};

// --- Paint API calls ---

/** Fetches all paints from the server. */
export const getPaints = async (): Promise<Paint[]> => {
  const response = await fetch(`${API_BASE_URL}/paints`);
  return handleResponse<Paint[]>(response);
};

/** Adds a new paint to the database. */
export const addPaint = async (paint: Omit<Paint, 'id'>): Promise<Paint> => {
  const response = await fetch(`${API_BASE_URL}/paints`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(paint),
  });
  return handleResponse<Paint>(response);
};

/** Updates an existing paint. */
export const updatePaint = async (id: string, paint: Partial<Omit<Paint, 'id'>>): Promise<Paint> => {
    const response = await fetch(`${API_BASE_URL}/paints/${id}`, {
      method: 'PUT',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(paint),
    });
    return handleResponse<Paint>(response);
  };
  
/** Deletes a paint by its ID. */
export const deletePaint = async (id: string): Promise<void> => {
  const response = await fetch(`${API_BASE_URL}/paints/${id}`, {
    method: 'DELETE',
  });
  if (!response.ok) {
    throw new Error('Failed to delete paint');
  }
};